spring.application.name=PhungLoc

# create and drop tables
spring.jpa.hibernate.ddl-auto=validate

# Oracle settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=C##PhungLoc
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.open-in-view=false
server.port=6767

